# Generated by Django 4.1.7 on 2023-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_late', models.BooleanField()),
                ('is_missing', models.SmallIntegerField()),
                ('is_passing', models.BooleanField()),
                ('tg_id', models.SmallIntegerField()),
            ],
        ),
    ]
