# Generated by Django 4.1.6 on 2023-03-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_missing',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_passing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='tg_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
