version: '3.3'
services:

  db:
    container_name: db
    # image: demianight/diploma_project:latest
    build: ../db/.
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
      - db_data:/app/database/
  bot:
    container_name: bot
    build: ../bot/.
    restart: always
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/redoc/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - bot
      - db

volumes:
  static_dir:
  media_dir:
  db_data: