version: '3.3'
services:

  db:
    container_name: db
    build: ../db/.
    restart: always
    volumes:

  bot:
    container_name: bot
    build: ../bot/.
    restart: always
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bot
      - db