version: '3.3'
services:

  db:
    container_name: db
    build: ../db/.
    restart: always
    ports:
     - "8000:8000"
    networks:
      - main

  # Uncomment when bot is done
  bot:
    container_name: bot
    build: ../bot/.
    restart: always
    depends_on:
      - db
    networks:
      - main

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
     - "6379:6379"

  celery:
    container_name: celery
    build: ../db/.
    command: celery -A db.celery worker -l info
    depends_on:
      - redis
      - db


networks:
  main: